'use client';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import { RefreshCw, Database, Settings, Plus, Save, Trash2, Percent } from 'lucide-react';
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid } from 'recharts';

type Holding={id?:string;ticker:string;name:string;risk_type:string;region:string;account_name?:string;quantity:number;avg_price:number;current_price:number;dividend_yield:number|string|null;dividend_cycle:string};
type Snap={id?:string;snapshot_date:string;account_name?:string|null;total_investment:number;total_value:number;total_profit:number;total_profit_rate:number;annual_dividend:number};
type DivLog={id?:string;dividend_month:string;ticker:string|null;amount:number};
const ACCOUNTS=['전체 계좌','삼성생명 퇴직연금','삼성증권 연금저축','한국투자증권 주식계좌'];
const defaultAccount=(ticker:string)=>ticker==='448290'?'삼성증권 연금저축':'삼성생명 퇴직연금';
const seed:Holding[]=[
{ticker:'441640',account_name:'삼성생명 퇴직연금',risk_type:'위험',region:'미국',name:'KODEX 미국배당커버드콜액티브',quantity:750,avg_price:13330,current_price:13525,dividend_yield:.0896,dividend_cycle:'월'},
{ticker:'494300',account_name:'삼성생명 퇴직연금',risk_type:'위험',region:'미국',name:'KODEX 미국나스닥100데일리커버드콜OTM',quantity:942,avg_price:10610,current_price:10930,dividend_yield:.1768,dividend_cycle:'월'},
{ticker:'0180V0',account_name:'삼성생명 퇴직연금',risk_type:'위험',region:'미국',name:'ACE 미국우주테크액티브',quantity:477,avg_price:13250,current_price:11950,dividend_yield:null,dividend_cycle:'없음'},
{ticker:'498400',account_name:'삼성생명 퇴직연금',risk_type:'위험',region:'한국',name:'KODEX 200타겟위클리커버드콜',quantity:440,avg_price:23882.48,current_price:27740,dividend_yield:.1133,dividend_cycle:'월'},
{ticker:'0015B0',account_name:'삼성생명 퇴직연금',risk_type:'위험',region:'미국',name:'KoAct 미국나스닥성장기업액티브',quantity:542,avg_price:22265.97,current_price:25435,dividend_yield:null,dividend_cycle:'없음'},
{ticker:'472150',account_name:'삼성생명 퇴직연금',risk_type:'위험',region:'한국',name:'TIGER 배당커버드콜액티브',quantity:326,avg_price:22971.2,current_price:28440,dividend_yield:.1477,dividend_cycle:'월'},
{ticker:'471040',account_name:'삼성생명 퇴직연금',risk_type:'위험',region:'미국',name:'KoAct 글로벌AI&로봇액티브',quantity:294,avg_price:33945,current_price:40070,dividend_yield:null,dividend_cycle:'없음'},
{ticker:'438080',account_name:'삼성생명 퇴직연금',risk_type:'안전',region:'미국',name:'ACE 미국S&P500미국채혼합50액티브',quantity:1268,avg_price:14840.61,current_price:15255,dividend_yield:.0219,dividend_cycle:'년'},
{ticker:'284430',account_name:'삼성생명 퇴직연금',risk_type:'안전',region:'한국',name:'KODEX 200미국채혼합',quantity:879,avg_price:22699,current_price:24910,dividend_yield:.0115,dividend_cycle:'월'},
{ticker:'472170',account_name:'삼성생명 퇴직연금',risk_type:'안전',region:'미국',name:'TIGER 미국테크TOP10채권혼합',quantity:1027,avg_price:14481,current_price:14365,dividend_yield:.0034,dividend_cycle:'년'},
{ticker:'440340',account_name:'삼성생명 퇴직연금',risk_type:'안전',region:'미국',name:'TIGER 글로벌멀티에셋TIF액티브',quantity:777,avg_price:12860.08,current_price:13250,dividend_yield:.0347,dividend_cycle:'월'}];
const won=(n:number)=>Math.round(n||0).toLocaleString('ko-KR')+'원';
const pct=(n:number)=>`${n>=0?'+':''}${(n*100).toFixed(2)}%`;
const priceText=(n:number)=>n>0?Math.round(n).toLocaleString('ko-KR'):'미조회';
const parseNumber=(v:any)=>Number(String(v??'').replace(/[^0-9.]/g,''))||0;
function normalizeYield(v:any){
 const n=Number(v||0);
 if(!n) return null;
 // 설정 화면 입력은 항상 % 기준입니다. 예: 1.15 입력 -> 1.15% = 0.0115 저장
 return n/100;
}
function storedYield(v:any){
 const n=Number(v||0);
 if(!n) return 0;
 // 과거 입력 오류 보정: 1 이상이면 100%가 아니라 % 입력값으로 간주합니다.
 return n>=1 ? n/100 : n;
}
const today=()=>new Date().toISOString().slice(0,10);
const month=()=>new Date().toISOString().slice(0,7);
export default function Page(){
 const [holdings,setHoldings]=useState<Holding[]>([]),[selectedAccount,setSelectedAccount]=useState('전체 계좌'),[snaps,setSnaps]=useState<Snap[]>([]),[logs,setLogs]=useState<DivLog[]>([]),[msg,setMsg]=useState(''),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const [form,setForm]=useState<Holding>({ticker:'',name:'',risk_type:'위험',region:'미국',account_name:'삼성생명 퇴직연금',quantity:0,avg_price:0,current_price:0,dividend_yield:'',dividend_cycle:'월'});
 const [div,setDiv]=useState({dividend_month:month(),ticker:'',amount:''});
 const allRows=useMemo(()=>holdings.map(h=>{const hasPrice=Number(h.current_price)>0; const effectivePrice=hasPrice?Number(h.current_price):Number(h.avg_price); const dy=storedYield(h.dividend_yield); const invest=Number(h.quantity)*Number(h.avg_price),value=Number(h.quantity)*effectivePrice,pl=hasPrice?value-invest:0;return{...h,account_name:h.account_name||defaultAccount(h.ticker),dividend_yield:dy,hasPrice,effectivePrice,investment:invest,value,pl,plRate:invest?pl/invest:0,annualDividend:value*dy}}),[holdings]);
 const rows=useMemo(()=>selectedAccount==='전체 계좌'?allRows:allRows.filter(r=>r.account_name===selectedAccount),[allRows,selectedAccount]);
 const accountSummaries=useMemo(()=>ACCOUNTS.filter(a=>a!=='전체 계좌').map(a=>{const list=allRows.filter(r=>r.account_name===a);const investment=list.reduce((s,r)=>s+r.investment,0),value=list.reduce((s,r)=>s+r.value,0),annual=list.reduce((s,r)=>s+r.annualDividend,0);return{account:a,count:list.length,investment,value,profit:value-investment,rate:investment?(value-investment)/investment:0,annual,monthly:annual/12,share:0}}).map(a=>({...a,share:allRows.reduce((s,r)=>s+r.value,0)?a.value/allRows.reduce((s,r)=>s+r.value,0):0})),[allRows]);
 const selectedAccountSummary=useMemo(()=>{if(selectedAccount==='전체 계좌'){const investment=allRows.reduce((s,r)=>s+r.investment,0),value=allRows.reduce((s,r)=>s+r.value,0),annual=allRows.reduce((s,r)=>s+r.annualDividend,0);return{account:'전체 계좌',count:allRows.length,investment,value,profit:value-investment,rate:investment?(value-investment)/investment:0,annual,monthly:annual/12,share:1};} return accountSummaries.find(a=>a.account===selectedAccount)||{account:selectedAccount,count:0,investment:0,value:0,profit:0,rate:0,annual:0,monthly:0,share:0};},[selectedAccount,allRows,accountSummaries]);
 const accountTickers=useMemo(()=>new Set(rows.map(r=>r.ticker)),[rows]);
 const filteredLogs=useMemo(()=>selectedAccount==='전체 계좌'?logs:logs.filter(l=>!l.ticker||accountTickers.has(l.ticker)),[logs,selectedAccount,accountTickers]);
 const filteredSnaps=useMemo(()=>snaps.filter(s=>selectedAccount==='전체 계좌'?(!s.account_name||s.account_name==='전체 계좌'):s.account_name===selectedAccount),[snaps,selectedAccount]);
 const totals=useMemo(()=>{const investment=rows.reduce((s,r)=>s+r.investment,0),value=rows.reduce((s,r)=>s+r.value,0),annual=rows.reduce((s,r)=>s+r.annualDividend,0),received=filteredLogs.reduce((s,l)=>s+Number(l.amount||0),0);return{investment,value,profit:value-investment,rate:investment?(value-investment)/investment:0,annual,monthly:annual/12,received}},[rows,filteredLogs]);
 const topRows=useMemo(()=>[...rows].sort((a,b)=>b.value-a.value).slice(0,5),[rows]);
 async function load(){setMsg('DB에서 불러오는 중...'); const [h,s,d]=await Promise.all([supabase.from('holdings').select('*').order('ticker'),supabase.from('daily_snapshots').select('*').order('snapshot_date'),supabase.from('dividend_logs').select('*').order('dividend_month',{ascending:false})]); if(h.error) setMsg('DB 연결 오류: '+h.error.message); else {setHoldings((h.data||[]) as Holding[]); setSnaps((s.data||[]) as Snap[]); setLogs((d.data||[]) as DivLog[]); setMsg('DB 연결 완료');}}
 useEffect(()=>{load()},[]);
 async function seedDb(){setBusy(true); const {error}=await supabase.from('holdings').upsert(seed,{onConflict:'ticker'}); setBusy(false); if(error) setMsg(error.message); else {setMsg('기본 ETF 데이터 저장 완료'); load();}}
 async function fetchPriceForTicker(ticker:string){try{const code=ticker.trim().toUpperCase(); const res=await fetch('/api/prices?codes='+encodeURIComponent(code)); const json=await res.json(); return Number(json.prices?.[code]||0);}catch{return 0;}}
 async function fetchYieldForTicker(ticker:string){try{const code=ticker.trim().toUpperCase(); const res=await fetch('/api/dividends?codes='+encodeURIComponent(code)); const json=await res.json(); const y=Number(json.yields?.[code]); return y>0?y:null;}catch{return null;}}
 async function saveHolding(h:Holding){const ticker=h.ticker.trim().toUpperCase(); if(!ticker||!h.name.trim()){setMsg('종목코드와 종목명을 입력해주세요.'); return;} setBusy(true); setMsg('종목 저장 중 · 현재가 조회 중...'); const [fetchedPrice,fetchedYield]=await Promise.all([fetchPriceForTicker(ticker),fetchYieldForTicker(ticker)]); const payload={ticker,name:h.name.trim(),risk_type:h.risk_type,region:h.region,account_name:h.account_name||'삼성생명 퇴직연금',quantity:+h.quantity,avg_price:+h.avg_price,current_price:fetchedPrice||0,dividend_yield:fetchedYield??normalizeYield(h.dividend_yield),dividend_cycle:h.dividend_cycle}; const {error}=await supabase.from('holdings').upsert(payload,{onConflict:'ticker'}); setBusy(false); if(error)setMsg(error.message); else {setForm({ticker:'',name:'',risk_type:'위험',region:'미국',account_name:'삼성생명 퇴직연금',quantity:0,avg_price:0,current_price:0,dividend_yield:'',dividend_cycle:'월'}); setMsg(`저장 완료 · 현재가 ${fetchedPrice?won(fetchedPrice):'미조회'} · 배당률 ${fetchedYield?((fetchedYield*100).toFixed(2)+'% 자동 반영'):'직접 입력값 반영'}`); load();}}
 async function delTicker(ticker:string){if(!confirm('삭제할까요?'))return; await supabase.from('holdings').delete().eq('ticker',ticker); load();}
 async function changePrice(ticker:string,price:number){setHoldings(v=>v.map(x=>x.ticker===ticker?{...x,current_price:price}:x)); await supabase.from('holdings').update({current_price:price}).eq('ticker',ticker);}
 async function saveSnapshot(){const payload={snapshot_date:today(),account_name:selectedAccount,total_investment:totals.investment,total_value:totals.value,total_profit:totals.profit,total_profit_rate:totals.rate,annual_dividend:totals.annual}; const {error}=await supabase.from('daily_snapshots').upsert(payload,{onConflict:'snapshot_date,account_name'}); if(error)setMsg(error.message); else {setMsg(`${selectedAccount} 오늘 일별 데이터 저장 완료`); load();}}
 async function addDividend(){const amount=Number(div.amount); if(!amount)return; const {error}=await supabase.from('dividend_logs').insert({dividend_month:div.dividend_month,ticker:div.ticker||null,amount}); if(error)setMsg(error.message); else {setDiv({...div,amount:''});load();}}
 async function delDividend(id?:string){if(!id)return; await supabase.from('dividend_logs').delete().eq('id',id); load();}
 async function updatePrices(){setBusy(true);setMsg('네이버금융에서 오늘 시세와 배당률 조회 중...'); try{const codes=rows.map(r=>r.ticker).join(','); const [priceRes,yieldRes]=await Promise.all([fetch('/api/prices?codes='+encodeURIComponent(codes)),fetch('/api/dividends?codes='+encodeURIComponent(codes))]); const priceJson=await priceRes.json(); const yieldJson=await yieldRes.json(); let count=0,yieldCount=0; const missed:string[]=[]; const yieldMissed:string[]=[]; for(const r of rows){const p=Number(priceJson.prices?.[r.ticker]); const y=Number(yieldJson.yields?.[r.ticker]); const patch:any={}; if(p>0){count++; patch.current_price=p;} else missed.push(r.ticker); if(y>0){yieldCount++; patch.dividend_yield=y;} else yieldMissed.push(r.ticker); if(Object.keys(patch).length) await supabase.from('holdings').update(patch).eq('ticker',r.ticker);} setMsg(`${count}개 시세 · ${yieldCount}개 배당률 갱신 완료${missed.length?` · 시세 미조회: ${missed.join(', ')}`:''}${yieldMissed.length?` · 배당률 미조회: ${yieldMissed.join(', ')}`:''}`); await load(); setTimeout(saveSnapshot,300);}catch(e:any){setMsg('시세/배당률 조회 실패: '+e.message)} finally{setBusy(false)}}
 async function updateDividendYields(){setBusy(true);setMsg('배당률 자동 조회 중...'); try{const codes=rows.map(r=>r.ticker).join(','); const res=await fetch('/api/dividends?codes='+encodeURIComponent(codes)); const json=await res.json(); let count=0; const missed:string[]=[]; for(const r of rows){const y=Number(json.yields?.[r.ticker]); if(y>0){count++; await supabase.from('holdings').update({dividend_yield:y}).eq('ticker',r.ticker);} else missed.push(r.ticker);} setMsg(`${count}개 종목 배당률 갱신 완료${missed.length?` · 미조회: ${missed.join(', ')}`:''}`); await load();}catch(e:any){setMsg('배당률 조회 실패: '+e.message)} finally{setBusy(false)}}
 const byMonth=useMemo(()=>filteredLogs.reduce((m:any,l)=>{m[l.dividend_month]=(m[l.dividend_month]||0)+Number(l.amount);return m},{}),[filteredLogs]);
 const tickerLabel=(ticker:string|null)=>{if(!ticker)return '전체/구분 없음'; const h=rows.find(r=>r.ticker===ticker); return h?`${h.name} · ${ticker}`:ticker;};
 return <main className="wrap"><header className="hero"><div><div className="eyebrow">JINNY TRADING</div><h1 className="title">ETF 포트폴리오</h1><p className="sub">Supabase DB 저장 · Vercel 배포 · 여러 기기 동기화</p></div><div className="toolbar"><button className="btn blue" onClick={updatePrices} disabled={busy}><RefreshCw size={15}/> 오늘 시세 업데이트</button><button className="btn green" onClick={saveSnapshot}><Save size={15}/> 오늘 기록 저장</button><button className="btn" onClick={updateDividendYields} disabled={busy}><Percent size={15}/> 배당률 업데이트</button><button className="btn" onClick={()=>setOpen(!open)}><Settings size={15}/> 설정</button></div></header>{msg&&<p className="warn">{msg}</p>}<section className="grid cards"><Metric label="총 투자금" value={won(totals.investment)}/><Metric label="총 평가금" value={won(totals.value)}/><Metric label="평가손익" value={won(totals.profit)} tone={totals.profit>=0?'gain':'loss'} sub={pct(totals.rate)}/><Metric label="월 예상 배당" value={won(totals.monthly)} sub={'누적 '+won(totals.received)}/></section>
 <section className="section"><div className="sectionHead"><h2>계좌별 대시보드</h2><span className="sub">전체 또는 계좌별로 투자금·평가금·손익·배당을 따로 확인합니다.</span></div><div className="accountTabs">{ACCOUNTS.map(a=><button key={a} className={'accountTab '+(selectedAccount===a?'active':'')} onClick={()=>setSelectedAccount(a)}>{a}</button>)}</div><div className="card accountDashboard"><div><div className="metricLabel">선택 계좌</div><div className="dashTitle">{selectedAccountSummary.account}</div><div className="sub">{selectedAccountSummary.count}개 종목 · 전체 평가금 대비 {(selectedAccountSummary.share*100).toFixed(1)}%</div></div><div className="dashMetrics"><Metric label="투자금" value={won(selectedAccountSummary.investment)}/><Metric label="평가금" value={won(selectedAccountSummary.value)}/><Metric label="손익" value={won(selectedAccountSummary.profit)} tone={selectedAccountSummary.profit>=0?'gain':'loss'} sub={pct(selectedAccountSummary.rate)}/><Metric label="월 예상 배당" value={won(selectedAccountSummary.monthly)}/></div><div className="accountBars">{accountSummaries.map(a=><div key={a.account} className="accountBarRow"><div><b>{a.account}</b><span>{won(a.value)} · {(a.share*100).toFixed(1)}%</span></div><div className="bar"><span style={{width:Math.min(100,a.share*100)+'%'}}/></div></div>)}</div></div><div className="grid accountGrid">{accountSummaries.map(a=><div className="card accountCard" key={a.account}><div className="metricLabel">{a.account}</div><div className="metric">{won(a.value)}</div><div className="sub">{a.count}개 종목 · 투자 {won(a.investment)}</div><div className={a.profit>=0?'gain':'loss'}><b>{won(a.profit)}</b> {pct(a.rate)}</div><div className="sub">월 예상 배당 {won(a.monthly)}</div></div>)}</div></section>
 <section className="section"><div className="sectionHead"><h2>{selectedAccount} 보유 종목</h2><span className="sub">{rows.length}개 종목</span></div><div className="card topHoldings"><div className="metricLabel">상위 보유 종목</div>{topRows.length?topRows.map(r=><div className="miniRow" key={r.ticker}><span>{r.name}<span className="sub"> · {r.ticker}</span></span><b>{won(r.value)}</b></div>):<div className="sub">선택 계좌에 보유 종목이 없습니다.</div>}</div><div className="card tableWrap"><table className="table"><thead><tr><th>계좌</th><th>구분</th><th>종목</th><th className="num">수량</th><th className="num">평균단가</th><th className="num">현재가</th><th className="num">평가금액</th><th className="num">손익</th><th className="num">배당</th><th></th></tr></thead><tbody>{rows.map(r=><tr key={r.ticker}><td><span className="accountPill">{r.account_name}</span></td><td><span className={'pill '+(r.risk_type==='위험'?'risk':'')}>{r.risk_type}</span></td><td><b>{r.name}</b><div className="sub">{r.region} · {r.ticker}</div></td><td className="num">{r.quantity.toLocaleString()}</td><td className="num">{Math.round(r.avg_price).toLocaleString()}</td><td className="num"><input className="price" inputMode="numeric" placeholder="미조회" value={r.current_price>0?Math.round(Number(r.current_price)).toLocaleString('ko-KR'):''} onChange={e=>changePrice(r.ticker,parseNumber(e.target.value))}/></td><td className="num"><b>{won(r.value)}</b></td><td className={'num '+(!r.hasPrice?'':r.pl>=0?'gain':'loss')}><b>{r.hasPrice?won(r.pl):'현재가 필요'}</b><div>{r.hasPrice?pct(r.plRate):'-'}</div></td><td className="num">{r.dividend_yield?`${(r.dividend_yield*100).toFixed(2)}% · ${r.dividend_cycle}`:'없음'}</td><td><button className="btn" onClick={()=>delTicker(r.ticker)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></section>
 <section className="section grid two"><div><div className="sectionHead"><h2>월별 배당 수령 내역</h2></div><div className="card"><div className="form" style={{gridTemplateColumns:'160px 1fr 160px auto'}}><input className="input" type="month" value={div.dividend_month} onChange={e=>setDiv({...div,dividend_month:e.target.value})}/><select className="input" value={div.ticker} onChange={e=>setDiv({...div,ticker:e.target.value})}><option value="">전체/구분 없음</option>{rows.map(r=><option key={r.ticker} value={r.ticker}>{r.name}</option>)}</select><input className="input" placeholder="수령 금액" value={div.amount} onChange={e=>setDiv({...div,amount:e.target.value})}/><button className="btn primary" onClick={addDividend}><Plus size={15}/> 추가</button></div><div className="miniList" style={{marginTop:14}}>{Object.entries(byMonth).map(([m,a]:any)=><div className="miniRow" key={m}><b>{m}</b><b>{won(a)}</b></div>)}{filteredLogs.slice(0,8).map(l=><div className="miniRow" key={l.id}><span>{l.dividend_month} · {tickerLabel(l.ticker)}</span><span>{won(l.amount)} <button className="btn" onClick={()=>delDividend(l.id)}>삭제</button></span></div>)}</div></div></div><div><div className="sectionHead"><h2>배당 현황</h2></div><div className="card miniList"><div className="miniRow"><span>연간 예상 배당</span><b>{won(totals.annual)}</b></div><div className="miniRow"><span>월 예상 배당</span><b>{won(totals.monthly)}</b></div><div className="miniRow"><span>누적 수령 배당</span><b>{won(totals.received)}</b></div><div><div className="sub">평가금 대비 배당률</div><div className="bar"><span style={{width:Math.min(100,(totals.annual/totals.value)*1000)+'%'}}/></div></div></div></div></section>
 <section className="section"><div className="sectionHead"><h2>{selectedAccount} 일별 자산 추이</h2><span className="sub">{filteredSnaps.length}일 기록</span></div><div className="card chart">{filteredSnaps.length>1?<ResponsiveContainer width="100%" height="100%"><LineChart data={filteredSnaps}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="snapshot_date"/><YAxis hide domain={['dataMin','dataMax']}/><Tooltip formatter={(v:any)=>won(Number(v))}/><Line type="monotone" dataKey="total_value" strokeWidth={3} dot={false}/></LineChart></ResponsiveContainer>:<span className="sub">선택한 계좌의 기록이 2일 이상 저장되면 그래프가 표시됩니다.</span>}</div></section>
 <section className={'section settings '+(open?'open':'')}><div className="sectionHead"><h2>설정</h2></div><div className="card"><div className="toolbar" style={{justifyContent:'flex-start',marginBottom:14}}><button className="btn primary" onClick={seedDb}><Database size={15}/> 기본 ETF 데이터 DB에 넣기</button><button className="btn" onClick={load}>DB 새로고침</button></div><div className="form"><input className="input" placeholder="종목코드" value={form.ticker} onChange={e=>setForm({...form,ticker:e.target.value})}/><input className="input" placeholder="종목명" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><select className="input" value={form.risk_type} onChange={e=>setForm({...form,risk_type:e.target.value})}><option>위험</option><option>안전</option></select><select className="input" value={form.region} onChange={e=>setForm({...form,region:e.target.value})}><option>미국</option><option>한국</option></select><select className="input" value={form.account_name} onChange={e=>setForm({...form,account_name:e.target.value})}>{ACCOUNTS.filter(a=>a!=='전체 계좌').map(a=><option key={a}>{a}</option>)}</select><input className="input" placeholder="수량" value={form.quantity||''} onChange={e=>setForm({...form,quantity:Number(e.target.value)})}/><input className="input" placeholder="평균단가" value={form.avg_price||''} onChange={e=>setForm({...form,avg_price:Number(e.target.value)})}/><input className="input" type="number" inputMode="decimal" step="0.01" min="0" placeholder="배당률 % 예: 1.15" value={form.dividend_yield??''} onChange={e=>setForm({...form,dividend_yield:e.target.value})}/><button className="btn green" onClick={()=>saveHolding(form)} disabled={busy}>저장 후 현재가 조회</button></div></div></section></main>}
function Metric({label,value,sub,tone}:{label:string;value:string;sub?:string;tone?:string}){return <div className="card"><div className="metricLabel">{label}</div><div className={'metric '+(tone||'')}>{value}</div>{sub&&<div className="sub">{sub}</div>}</div>}
